---
- hosts: all
  become: True
  tasks:
    - name: update cache
      package: update_cache=yes
      changed_when: false
    - name: "Installing pip"
      package: name={{ item  }} state=present update_cache=no
      with_items:
        - python-pip
        - git
        - apache2
        - libapache2-mod-wsgi
        - apache2-utils

    - name: "Install python packages"
      pip: name={{ item }}
      with_items:
        - flask
        - Werkzeug
    - name: "Cloning git repo "
      git: repo=https://bitbucket.org/azneita/devops-challenge.git
           dest=/webapps/devops
           force=yes
           recursive=no
    - name: "Creating symbolic link"
      file:
        src: "/webapps/devops/"
        dest: "/var/www/devops"
        state: link

    - name: "copying wsgi file"
      template: 
        src: flask.wsgi.j2
        dest: /var/www/devops/flask.wsgi

    - template:
        src: flask.config.j2
        dest: /etc/apache2/sites-available/flask.conf

    - command: "{{ item }}"
      with_items:
        - a2ensite flask.conf
        - a2dissite 000-default.conf
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
